config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),  # ссылаемся на shop.urls, там джанго будет искать нужный адрес
    path('users/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from shop.views import (

    PrinterDetailView,
    BwPrintersListView,
    ColorPrintersListView,
    TonersListView,
    CartView,
    AddToCartView,
    HomeListView,
    DeleteFromCartView,
    ChangeQtyView,
    CheckoutView,
    MakeOrderView,
    SearchView,

    stock,
    contact,

)


urlpatterns = [
    path('', HomeListView.as_view(), name='shop-home'),
    path('stock/', stock, name='stock'),
    path('contact/', contact, name='contact'),
    path('printer/<slug>/', PrinterDetailView.as_view(), name='printer-detail'),
    path('bw-printers/', BwPrintersListView.as_view(), name='bw-printers'),
    path('color-printers/', ColorPrintersListView.as_view(), name='color-printers'),
    path('toners/', TonersListView.as_view(), name='toners'),
    path('cart/', CartView.as_view(), name='cart'),
    path('add-to-cart/toner/<slug>/', AddToCartView.as_view(), name='add_to_cart'),
    path('remove-from-cart/toner/<slug>/', DeleteFromCartView.as_view(), name='delete_from_cart'),
    path('change-qty/toner/<slug>/', ChangeQtyView.as_view(), name='change_qty'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('make-order/', MakeOrderView.as_view(), name='make_order'),
    path('search/', SearchView.as_view(), name='search'),

]

shop/models.py
from PIL import Image
from django.urls import reverse
from django.contrib.auth import get_user_model
from users.models import Profile
from django.utils import timezone
from django.db import models
from .utils import currency

User = get_user_model()


class Category(models.Model):
    title = models.CharField(max_length=255, verbose_name='Категория товара')
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title


class Printer(models.Model):
    cat = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория товара')
    title = models.CharField(max_length=255, verbose_name='Наименование')
    slug = models.SlugField(unique=True)
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Цена')
    image = models.ImageField(default="default.png", upload_to="printer_pics")
    specification = models.FileField(default="default.pdf", upload_to="printer_manuals")
    color = models.BooleanField(default=True, verbose_name='Цветной')
    show_main = models.BooleanField(default=False, verbose_name='Показывать на главной')

    def __str__(self):
        return f'{self.cat} : {self.title}'

    # def save(self, **kwargs):
    #     super().save(**kwargs)
    #     img = Image.open(self.image.path)
    #     if img.height > 300 or img.width > 450:
    #         output_size = (300, 450)
    #         img.thumbnail(output_size)
    #         img.save(self.image.path)

    def get_absolute_url(self):
        return reverse("printer-detail", kwargs={"slug": self.slug})


class Toner(models.Model):
    COLOR_CHOICES = (
        ('C', 'Cyan'),
        ('M', 'Magenta'),
        ('Y', 'Yellow'),
        ('K', 'Black'),
    )

    cat = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория товара', default=2)
    prtr = models.ForeignKey(Printer, on_delete=models.CASCADE, default=1, verbose_name='Подходит для',
                             related_name='toner_printer')
    title = models.CharField(max_length=255, verbose_name='Наименование')
    slug = models.SlugField(unique=True)
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Цена')
    image = models.ImageField(default="default.png", upload_to="toner_pics")
    weight = models.DecimalField(max_digits=4, decimal_places=0, verbose_name='Вес')
    color = models.CharField(max_length=1, choices=COLOR_CHOICES, default='K', verbose_name='Цвет')

    def __str__(self):
        return f'{self.cat} : {self.title}'

    @property
    def class_for_template(self):
        if self.color == 'K':
            return 'table-secondary'
        elif self.color == 'Y':
            return 'table-warning'
        elif self.color == 'M':
            return 'table-danger'
        else:
            return 'table-primary'


class Cart(models.Model):
    owner = models.ForeignKey(Profile, verbose_name='Владелец', on_delete=models.CASCADE)
    product = models.ManyToManyField('CartProduct', blank=True, related_name='related_cart')
    total_qty = models.PositiveIntegerField(default=0)  # это поле решил не использовать
    final_price = models.DecimalField(max_digits=9, decimal_places=2, default=0,
                                      verbose_name='Общая цена')  # это поле решил не использовать
    time_create = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(f'Корзина для {self.owner}')

    # При создании корзины вылетали ошибки

    # def save(self, *args, **kwargs):
    #     # super().save(*args, **kwargs)
    #     cart_data = self.product.aggregate(models.Sum('final_price'), models.Count('id'))
    #     if cart_data.get('final_price__sum'):
    #         self.final_price = cart_data['final_price__sum']
    #     else:
    #         self.final_price = 0
    #     self.total_qty = cart_data['id__count']
    #     super().save(*args, **kwargs)

    @property
    def f_price(self):
        cart_data = self.product.aggregate(models.Sum('final_price'), models.Count('id'))
        if cart_data.get('final_price__sum'):
            self.final_price = cart_data['final_price__sum']
        else:
            self.final_price = 0
        return self.final_price


class CartProduct(models.Model):
    user = models.ForeignKey(Profile, verbose_name='Покупатель', on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, verbose_name='Корзина', on_delete=models.CASCADE, related_name='related_product')
    product_toner = models.ForeignKey(Toner, on_delete=models.CASCADE, verbose_name='Тонер в корзине')
    qty = models.PositiveIntegerField(default=1)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Общая цена')

    def __str__(self):
        return f'Продукт: {self.product_toner.title} для корзины {self.user}'

    def save(self, *args, **kwargs):
        self.final_price = self.qty * float(self.product_toner.price) * float(self.user.discount) * currency[
            'euro_ex_rate']
        super().save(*args, **kwargs)

    @property
    def discount_price(self):
        return self.final_price / self.qty


class Order(models.Model):
    STATUS_NEW = 'Новый'
    STATUS_IN_PROGRESS = 'В обработка'
    STATUS_READY = 'Готов к отгрузке'
    STATUS_COMPLETED = 'Выполнен'

    DELIVERY_NEED = 'Нужна доставка'
    DELIVERY_PICKUP = 'Самовывоз'

    STATUS_CHOICES = (
        (STATUS_NEW, 'Новый'),
        (STATUS_IN_PROGRESS, 'В обработке'),
        (STATUS_READY, 'Готов к отгрузке'),
        (STATUS_COMPLETED, 'Выполнен')
    )

    DELIVERY_CHOICES = (
        (DELIVERY_NEED, 'Нужна доставка'),
        (DELIVERY_PICKUP, 'Самовывоз')
    )

    customer = models.ForeignKey(Profile, verbose_name='Покупатель', related_name='related_orders',
                                 on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, verbose_name='Корзина', on_delete=models.CASCADE, null=True, blank=True)
    first_name = models.CharField(max_length=255, verbose_name='Имя')
    last_name = models.CharField(max_length=255, verbose_name='Фамилия')
    phone = models.CharField(max_length=20, verbose_name='Телефон')
    address = models.CharField(max_length=255, verbose_name='Адрес', null=True, blank=True)
    status = models.CharField(max_length=100, verbose_name='Статус заказа', choices=STATUS_CHOICES, default=STATUS_NEW)
    delivery = models.CharField(max_length=100, verbose_name='Тип доставки', choices=DELIVERY_CHOICES,
                                default=DELIVERY_PICKUP)
    comment = models.TextField(verbose_name='Комментарий к заказу', null=True, blank=True)
    created_at = models.DateTimeField(auto_now=True, verbose_name='Дата создания заказа')
    order_date = models.DateField(default=timezone.now, verbose_name='Дата доставки (самовывоза) заказа')

    def __str__(self):
        return f'Заказ №{self.id} ({self.customer.company_name}) - {self.status}'

shop/forms.py
from django import forms

from shop.models import Order


class OrderForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['order_date'].label = 'Дата доставки (самовывоза) заказа'


    order_date = forms.DateTimeField(widget=forms.TextInput(attrs={'type': 'date'}))

    class Meta:
        model = Order
        fields = (
            'first_name', 'last_name', 'phone', 'address', 'delivery', 'order_date', 'comment'
        )
        widgets = {
            'comment': forms.Textarea(attrs={'rows': 4}),
        }


class ContactForm(forms.Form):
    subject = forms.CharField(label='Тема сообщения', widget=forms.TextInput(attrs={'class': 'form-control'}))
    # sender = forms.EmailField(label = 'Ваш email', widget = forms.EmailInput(attrs = {'class': 'form-control'}))
    content = forms.CharField(label='Сообщение', widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 5}))

shop/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.views.generic import DetailView, ListView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.db import transaction
from django.core.mail import send_mail
from .forms import OrderForm, ContactForm
from shop.models import *
from users.models import Profile
from .utils import currency


class SearchView(ListView):
    template_name = 'shop/search.html'
    context_object_name = 'toners'

    def get_queryset(self):
        return Toner.objects.filter(title__icontains=self.request.GET.get('s'))

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class CartView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        customer = Profile.objects.get(user=request.user)
        cart = Cart.objects.get(owner=customer)
        context = {
            'cart': cart,
        }
        return render(request, 'shop/cart.html', context)


class CheckoutView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        customer = Profile.objects.get(user=request.user)
        cart = Cart.objects.get(owner=customer)
        form = OrderForm(request.POST or None)
        context = {
            'cart': cart,
            'form': form,
        }
        return render(request, 'shop/checkout.html', context)


class MakeOrderView(LoginRequiredMixin, View):

    @transaction.atomic
    def post(self, request, *args, **kwargs):
        form = OrderForm(request.POST or None)
        if form.is_valid():
            new_order = form.save(commit=False)
            new_order.customer = Profile.objects.get(user=request.user)
            new_order.first_name = form.cleaned_data['first_name']
            new_order.last_name = form.cleaned_data['last_name']
            new_order.phone = form.cleaned_data['phone']
            new_order.address = form.cleaned_data['address']
            new_order.delivery = form.cleaned_data['delivery']
            new_order.order_date = form.cleaned_data['order_date']
            cart = Cart.objects.get(owner=new_order.customer)
            new_order.comment = form.cleaned_data['comment'] + f'\n---------------------\n'

            # Данным циклом решаю несколько проблем:
            # 1) Вывожу в поле комментариев к заказу информацию о заказе.
            #    Менеджеру не придется лезть и искать корзину, связанную с заказом.
            # 2) Очищаю корзину, чтобы она отображалась как пустая.

            for i in cart.product.all():
                new_order.comment += f'{str(i.product_toner)} - {i.qty} шт. - {i.final_price} руб.\n'
                i.delete()
                cart.save()

            new_order.save()
            messages.add_message(request, messages.INFO, 'Спасибо за заказ! Менеджер с Вами свяжется')
            send_mail(
                f'Новый заказ на сайте №{new_order.pk} ({new_order.customer.company_name})',
                new_order.comment, 'djangofreetest@gmail.com', ['zhurid.dk@gmail.com'], fail_silently=True
            )

            return HttpResponseRedirect('/')
        return HttpResponseRedirect('/checkout/')


class AddToCartView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        print(kwargs)
        product_slug = kwargs.get('slug')
        customer = Profile.objects.get(user=request.user)
        cart = Cart.objects.get(owner=customer)
        product = Toner.objects.get(slug=product_slug)
        cart_product, created = CartProduct.objects.get_or_create(
            user=cart.owner, cart=cart, product_toner=product,
        )
        if created:
            cart.product.add(cart_product)
            cart.save()
            messages.add_message(request, messages.INFO, f"Тонер {product.title} добавлен в корзину")
        else:
            messages.add_message(request, messages.INFO, f"Тонер {product.title} уже в корзине!")
        print(request)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class DeleteFromCartView(View):

    def get(self, request, *args, **kwargs):
        product_slug = kwargs.get('slug')
        customer = Profile.objects.get(user=request.user)
        cart = Cart.objects.get(owner=customer)
        product = Toner.objects.get(slug=product_slug)
        cart_product = CartProduct.objects.get(
            user=cart.owner, cart=cart, product_toner=product,
        )
        cart.product.remove(cart_product)
        cart_product.delete()
        cart.save()
        messages.add_message(request, messages.INFO, f"Тонер {product.title} удален из корзины")
        return HttpResponseRedirect('/cart/')


class ChangeQtyView(View):

    def post(self, request, *args, **kwargs):
        product_slug = kwargs.get('slug')
        customer = Profile.objects.get(user=request.user)
        cart = Cart.objects.get(owner=customer)
        product = Toner.objects.get(slug=product_slug)
        cart_product = CartProduct.objects.get(
            user=cart.owner, cart=cart, product_toner=product,
        )
        qty = int(request.POST.get('qty'))
        if cart_product.qty != qty:
            cart_product.qty = qty
            cart_product.save()
            cart.save()
            messages.add_message(request, messages.INFO, f"Количество тонера {product.title} изменено на {qty} шт.")
        return HttpResponseRedirect('/cart/')


class PrinterDetailView(DetailView):
    model = Printer
    context_object_name = 'printer'


class BwPrintersListView(ListView):
    model = Printer
    queryset = Printer.objects.filter(color=False)
    template_name = 'shop/printers.html'
    context_object_name = 'printers'
    paginate_by = 4
    ordering = ['-price']


class ColorPrintersListView(ListView):
    model = Printer
    queryset = Printer.objects.filter(color=True)
    template_name = 'shop/printers.html'
    context_object_name = 'printers'
    paginate_by = 4
    ordering = ['-price']


class TonersListView(ListView):
    model = Toner
    template_name = 'shop/toners_table.html'
    context_object_name = 'toners'
    paginate_by = 12
    ordering = ['price']

    def get_context_data(self, **kwargs):

        context = super(TonersListView, self).get_context_data(**kwargs)
        for toner in context['object_list']:
            toner.price = self.calculate_discount_price(self, toner.price)
        return context

    @staticmethod
    def calculate_discount_price(self, price):
        price = float(price)
        if self.request.user.is_authenticated:
            user = self.request.user
            discount = float(user.profile.discount)
            return price * discount * currency['euro_ex_rate']
        return price * currency['euro_ex_rate']


class HomeListView(ListView):
    model = Printer
    template_name = 'shop/home.html'
    context_object_name = 'printers'
    ordering = ['-price']


# def home(request):
#     return render(request, 'shop/home.html', {'printers': Printer.objects.all()})


def stock(request):
    return render(
        request,
        'shop/stock.html',
        {}
    )


# def rate(request):
#     return render(
#         request,
#         'shop/currency.html',
#         {'currency': currency}
#     )


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            mail = send_mail(form.cleaned_data['subject'], form.cleaned_data['content'], 'djangofreetest@gmail.com', ['zhurid.dk@gmail.com'], fail_silently=True)
            if mail:
                messages.success(request, 'Письмо отправлено!')
                return redirect('shop-home')
            else:
                messages.warning(request, 'Ошибка отправки!')
        else:
            messages.warning(request, 'Ошибка регистрации!')
    else:
        form = ContactForm()
    return render(request, 'shop/contact.html', {'form': form})

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Konica Minolta</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" type="text/css" href="{% static 'shop/styles.css' %}">

    </head>

    <body id="top">

        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="/">
			        <img border="0" src="{% static 'img/km_logo.png' %}">
			    </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link" aria-current="page" href="/">Главная</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle active" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Каталог товаров</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'toners' %}">Тонер</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="{% url 'color-printers' %}">Цветные МФУ</a></li>
                                <li><a class="dropdown-item" href="{% url 'bw-printers' %}">Чёрно-белые МФУ</a></li>
                            </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'stock' %}">Акции</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'contact' %}">Контакты</a></li>
                        {% if user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link active" href="{% url 'profile' %}">Профиль</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Выход</a></li>
                        {% else %}
                            <li class="nav-item"><a class="nav-link active" href="{% url 'login' %}">Войти</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'register' %}">Регистрация</a></li>
                        {% endif %}
                    </ul>

                    {% include "shop/currency.html" %}

                    {% if user.is_authenticated %}
                        <form class="d-flex">
                            <a class="btn btn-outline-primary" href="{% url 'cart' %}">
                                <i class="bi-cart-fill me-1"></i>
                                Корзина
                                <span class="badge bg-primary text-white ms-1 rounded-pill">{{ user.profile.cart_set.first.product.count }}</span>
                            </a>
                        </form>
                    {% endif %}
                </div>
            </div>
        </nav>
        <!-- Header-->
        <header class="bg-primary py-5">
            <div class="container px-4 px-lg-5 my-5">
<!--                <p class="admin_href"><a href="/admin/" style="color: white;">Admin</a></p>-->
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Konica Minolta</h1>
                    <p class="lead fw-normal text-white-50 mb-0">Полноцветные и чёрно-белые системы печати</p>
                </div>
            </div>
        </header>
        <!-- Section-->
        {% if messages %}
            {% for message in messages %}
                <div class='alert alert-{{ message.tags }}'>
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        {% block content %}{% endblock %}
        <!-- Footer-->
        <footer class="py-5 bg-primary">
            <div class="container"><a href="#top"><p class="m-0 text-center text-white">Вернуться наверх</p></a></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->

    </body>
</html>

shop/templates/shop/checkout.html
{% extends 'shop/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <h3 class="text-center mt-5 mb-5">Оформление заказа</h3>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Наименование</th>
                        <th scope="col">Изображение</th>
                        <th scope="col">Цена</th>
                        <th scope="col">Количество</th>
                        <th scope="col">Общая цена</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in cart.product.all %}
                        <tr>
                            <th scope="row">{{ item.product_toner.title }}</th>
                            <td><img src="{{ item.product_toner.image.url }}" class="img-fluid" style="height:100px"></td>
                            <td>{{ item.discount_price|floatformat:2 }} руб.</td>
                            <td>{{ item.qty }}</td>
                            <td>{{ item.final_price }} руб.</td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <td colspan="2"></td>
                        <td></td>
                        <td>Итого:</td>
                        <td><strong>{{ cart.f_price|floatformat:2 }} руб.</strong></td>
                    </tr>
                </tbody>
            </table>
            <h3 class="text-center mt-5 mb-5">Форма заказа</h3>
            <form action="{% url 'make_order' %}" method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" class="btn btn-success btn-lg btn-block mb-3" style="width:100%" value="Оформить заказ">
            </form>

        </div>
    </section>

{% endblock content %}

shop/templates/shop/currency.html
<table style="margin-right: 40px; font-size: 14px; border-collapse: separate; border-spacing: 10px 0px;">
    <tbody>
        <tr>
            <td align="left" colspan="2">EUR</td>
            <td style="font-weight: normal; text-align:right;">{{ euro_ex_rate|floatformat:4 }}</td>
        </tr>
        <tr>
            <td align="left" colspan="2">USD</td>
            <td align="right">{{ usd_ex_rate|floatformat:4 }}</td>
        </tr>
    </tbody>
</table>

shop/templates/shop/search.html
{% extends 'shop/base.html' %}
{% block content %}
    <section class="py-1 mb-5">
        <div class="container px-4 px-lg-5 mt-5">
            <h3 class="text-center mt-1 mb-5">Оригинальный тонер для принтеров и МФУ Konica Minolta</h3>
            <table class="table">
                <thead>
                    <tr class="table-dark">
                        <th scope="col">Наименование</th>
                        <th scope="col">Цвет</th>
                        <th scope="col">Применимость</th>
                        <th scope="col">Вес тубы (г)</th>
                        <th scope="col">Цена</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for toner in toners %}
                        {% if toner.price != 9999 %}
                            {% if toner.color == 'K' %}
                                <tr class="table-secondary">
                                    <th scope="row">{{ toner.title }}</th>
                                    <td>{{ toner.get_color_display }}</td>
                                    <td><a href="{% url 'printer-detail' toner.prtr.slug %}"> Konica Minolta {{ toner.prtr.title }}</a></td>
                                    <td>{{ toner.weight }}</td>
                                    <td>{{ toner.price }} руб.</td>
                                    <td>
                                        <a href="{% url 'add_to_cart' slug=toner.slug %}">
                                            <button class="btn btn-success">Добавить в корзину</button>
                                        </a>
                                    </td>
                                </tr>
                            {% endif %}
                            {% if toner.color == 'C' %}
                                <tr class="table-primary">
                                    <th scope="row">{{ toner.title }}</th>
                                    <td>{{ toner.get_color_display }}</td>
                                    <td><a href="{% url 'printer-detail' toner.prtr.slug %}"> Konica Minolta {{ toner.prtr.title }}</a></td>
                                    <td>{{ toner.weight }}</td>
                                    <td>{{ toner.price }} руб.</td>
                                    <td>
                                        <a href="{% url 'add_to_cart' slug=toner.slug %}">
                                            <button class="btn btn-success">Добавить в корзину</button>
                                        </a>
                                    </td>
                                </tr>
                            {% endif %}
                            {% if toner.color == 'M' %}
                                <tr class="table-danger">
                                    <th scope="row">{{ toner.title }}</th>
                                    <td>{{ toner.get_color_display }}</td>
                                    <td><a href="{% url 'printer-detail' toner.prtr.slug %}"> Konica Minolta {{ toner.prtr.title }}</a></td>
                                    <td>{{ toner.weight }}</td>
                                    <td>{{ toner.price }} руб.</td>
                                    <td>
                                        <a href="{% url 'add_to_cart' slug=toner.slug %}">
                                            <button class="btn btn-success">Добавить в корзину</button>
                                        </a>
                                    </td>
                                </tr>
                            {% endif %}
                            {% if toner.color == 'Y' %}
                                <tr class="table-warning">
                                    <th scope="row">{{ toner.title }}</th>
                                    <td>{{ toner.get_color_display }}</td>
                                    <td><a href="{% url 'printer-detail' toner.prtr.slug %}"> Konica Minolta {{ toner.prtr.title }}</a></td>
                                    <td>{{ toner.weight }}</td>
                                    <td>{{ toner.price }} руб.</td>
                                    <td>
                                        <a href="{% url 'add_to_cart' slug=toner.slug %}">
                                            <button class="btn btn-success">Добавить в корзину</button>
                                        </a>
                                    </td>
                                </tr>
                            {% endif %}
                        {% else %}
                            <tr class="table-light">
                                <th scope="row">{{ toner.title }}</th>
                                <td>{{ toner.get_color_display }}</td>
                                <td><a href="{% url 'printer-detail' toner.prtr.slug %}"> Konica Minolta {{ toner.prtr.title }}</a></td>
                                <td>{{ toner.weight }}</td>
                                <td> - - - - - </td>
                                <td> Нет в наличии </td>
                            </tr>
                        {% endif %}
                    {% empty %}
                        <p>По вашему запросу ничего не найдено. Проверьте правильность ввода</p>
                    {% endfor %}
                </tbody>
            </table>
            {% if is_paginated %}
                {% if page_obj.has_previous %}
                    <a class="btn btn-outline-primary mb-4" href="?page=1">Первая</a>
                    <a class="btn btn-outline-primary mb-4" href="?page={{ page_obj.previous_page_number }}"><<</a>
                {% endif %}
                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                        <a class="btn btn-primary mb-4" href="?page={{ num }}">{{ num }}</a>
                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                        <a class="btn btn-outline-primary mb-4" href="?page={{ num }}">{{ num }}</a>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <a class="btn btn-outline-primary mb-4" href="?page={{ page_obj.next_page_number }}">>></a>
                    <a class="btn btn-outline-primary mb-4" href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
                {% endif %}
            {% endif %}
        </div>
    </section>
{% endblock %}

shop/templates/shop/stock.html
{% extends 'shop/base.html' %}
{% block content %}
    <br>
    <h2 align="center">На данный момент акций нет</h2>
    <br>
{% endblock %}